config/routes.rb
Rails.application.routes.draw do
  # ...

  devise_for :users

  root 'pages#home'

  resources :posts
  resources :subscribers
  resources :profiles, only: [:show, :destroy]
  # Ajoutez les routes pour gérer les abonnements et les newsletters

  # Pour afficher la liste des newsletters disponibles
  resources :newsletters, only: [:index, :show]

  # Pour permettre aux utilisateurs de s'abonner et se désabonner
  resources :subscriptions, only: [:create, :destroy]

  # Pour envoyer une newsletter (vous pouvez protéger cette route par exemple)
  post 'newsletters/:id/send', to: 'newsletters#send_newsletter', as: 'send_newsletter'

  # ...
  post '/attachments', to: 'attachments#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_many :subscriptions

  validates :subject, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :user
  has_one_attached :image
  has_one_attached :video

  # Validations
  validates :title, presence: true
  validates :category, presence: true
  validates :content, presence: true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  has_many :subscriptions
  
  validates :surname, presence: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :category, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :subscriber
  belongs_to :newsletter
end

app/models/user.rb
class User < ApplicationRecord
  before_create :set_default_user_type
  # Associations
  has_many :posts, dependent: :destroy
  has_one_attached :avatar

  # Validations
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :user_type, presence: true, inclusion: { in: %w[admin poster user] }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
  user_type == "admin"
  end

  def poster?
    user_type == "poster"
    end

  include Administration

  validate :check_user_type_change, on: :update

  def check_user_type_change
    errors.add(:user_type, "Vous ne pouvez pas changer le user_type.") if user_type_changed? && !can_change_user_type?
  end

  private

  def set_default_user_type
    self.user_type ||= 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  include Pundit::Authorization

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/newsletter_controller.rb
# app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  def index
    @newsletters = Newsletter.all
  end

  def new
    @newsletter = Newsletter.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        # Tell the NewsletterMailer to send a welcome email after save
        NewsletterMailer.welcome_subscriber(@subscriber).deliver_later

        format.html { redirect_to root_path, notice: 'Votre inscription a été prise en compte.' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { redirect_to root_path, alert: 'Vous êtes déjà inscrit à notre Newsletter !' }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def newsletter_params
    params.require(:newsletter).permit(:subject, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.order(created_at: :desc)
    @subscriber = Subscriber.new
  end

 def create
  @subscriber = Subscriber.new(subscriber_params)
  if @subscriber.save
    cookies[:saved_lead] = true
    redirect_to root_path, notice: "Votre inscription a été prise en compte."
  else
    # Traiter les erreurs de validation si nécessaire
    redirect_to root_path, alert: "Il y a eu un problème lors de votre inscription."
  end
end

  private

  def subscriber_params
    params.require(:subscriber).permit(:surname, :name, :email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Pundit::Authorization

  def index
     @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    skip_authorization
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    authorize @post

    if @post.save
      @post.image.attach(params[:post][:image])
      @post.video.attach(params[:post][:video])
      redirect_to root_path, notice: "Le post a été créé avec succès."
    else
      render 'new'
    end
  end


  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post

    if @post.update(post_params)
      # Utilisez Turbo Streams pour mettre à jour la fenêtre Turbo Frame dans la vue d'édition
      redirect_to root_path, notice: "Le post a été mis à jour avec succès."
    else
      # Redirige vers l'action d'édition en cas d'erreur
      render :edit
    end
  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    authorize @post
    redirect_to root_path, notice: "L'article a été supprimé avec succès."
  end

  private

  def post_params
    params.require(:post).permit(:title, :category, :content, :image) # Ajoutez d'autres attributs autorisés si nécessaire
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @subscriber = Subscriber.new
    @user = current_user
    authorize @user
    @posts = Post.where(user_id: current_user.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    authorize @post
    redirect_to root_path, notice: "L'article a été supprimé avec succès."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cara.news</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "shared/navbar" %>
    <%= csrf_meta_tags %>

    <!-- Place the first <script> tag in your HTML's <head> -->
    <script src="https://cdn.tiny.cloud/1/mpieyjs1df9b8d2xzmi1msvy4wd7ybe4a81t09uhj0ky6qoe/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
  </head>

  <body>
        <% if notice %>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger">
      <%= alert %>
    </div>
    <% end %>
    <%= yield %>
    <!-- Place the following <script> and <textarea> tags your HTML's <body> -->
    <script>
      tinymce.init({
        selector: 'textarea',
        plugins: 'ai tinycomments mentions anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed permanentpen footnotes advtemplate advtable advcode editimage tableofcontents mergetags powerpaste tinymcespellchecker autocorrect a11ychecker typography inlinecss',
        toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
        mergetags_list: [
          { value: 'First.Name', title: 'First Name' },
          { value: 'Email', title: 'Email' },
        ],
        ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
      });
    </script>
  </body>
        <%= render "shared/footer" %>
</html>

app/views/pages/home.html.erb
<!-- Main container -->
<% if cookies[:saved_subscriber] %>
  <div class="success-message">
    <p>Vous êtes inscrit !</p>
  </div>
<% else %>
  <div class="newsletter-form">
    <%= form_for @subscriber do |f| %>
      <%= f.text_field :name, placeholder: "Nom", class: "input-field" %>
      <%= f.text_field :surname, placeholder: "Prénom", class: "input-field" %>
      <%= f.email_field :email, placeholder: "E-mail", class: "input-field" %>
      <%= f.select :category, options_for_select(["Actualité", "Culture"]), {}, class: "input-field" %>
      <%= f.submit "S'inscrire à la Newsletter", class: "submit-button" %>
    <% end %>
  </div>
<% end %>

<div class="container py-4">
  <h4 class="rounded-background">Derniers articles en ligne</h4>
      <div class="mt-3 cards-hp mx-auto">
        <% @posts.each do |post| %>
          <div class="card-trip">
            <% if post.image.attached? %>
              <% if post.image.variable? %>
                <%= image_tag post.image %>
            <% else %>
              <video controls>
                <source src="<%= url_for(post.image) %>" type="video/mp4">
                Your browser does not support the video tag.
              </video>
            <% end %>
          <% end %>
            <div class="card-trip-infos">
              <div>
                 <strong><%= link_to post[:title], post_path(post[:id]) %></strong>
              </div>
              <p class="card-trip-pricing"><%= post[:category] %></p>
            </div>
          </div>
        <% end %>
      </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Actuellement en construction
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn">
      <i class="fas fa-search"></i>
    </button>
  </div>
<% end %>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
         <% if current_user.user_type.in?(['admin', 'poster']) %>
            <!-- Bouton spécifique pour les administrateurs et posteurs -->
            <li class="nav-item">
              <%= link_to "Créer un article", new_post_path, class: "nav-link" %>
            </li>
          <% end %>
          <% if current_user.user_type.in?(['admin']) %>
            <!-- Bouton spécifique pour les administrateurs et posteurs -->
            <li class="nav-item">
              <%= link_to "Liste", subscribers_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
             <a class="nav-link" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="nav-item">Mon Compte</div>
             </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", profile_path(current_user), class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>